# Site settings

title: FabMarket 
email: market@fablabbcn.org
description: "Fab Shop is an online market for open source design quality products can be customized, resourced, fabricated and sold locally supporting communities."
url: http://127.0.0.1:4000/


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 231f20
  secondary: 231f20
  whites: FAFAFA

fonts: 
  primary: Lato 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: envelope
    url: mailto:market@fablabbcn.org
  - title: twitter
    url: https://twitter.com/fablabbcn
  - title: facebook
    url: https://www.facebook.com/FabLab.BCN/  


# Team names, titles and social links
people:
- name: 
  pic: 1
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: 
  pic: 2
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: 
  pic: 3
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #


# Postal address (add as many lines as necessary)
address:
  - line: Barcelona
  - line: Pujades 102, 08005

# Build settings
markdown: kramdown
permalink: pretty

# Paypal code
paypal:
  merchant_id: BRJRD6WSME3EC
  callback_url: http://market.fablabs.io/thank-you/

# Gems
gems:
  - kramdown


urlimg: '/img/' 
